services:
  postgres:
    image: postgres:latest
    container_name: postgres-docker
    environment:
      POSTGRES_USER: ${DATABASE_NAME_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - "5432:5432"

    expose:
      - "5432"

  prisma:
    container_name: prisma-my-platform
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - 3000:3000

    volumes:
      - ./:/app
    command: >
      bash -c '
        npx prisma generate --schema prisma/schema.prisma
        npx prisma migrate dev
        npx prisma db push
        yarn dev
      '
    depends_on:
      - postgres

    environment:
      PRISMA_CONFIG: |
        port: 3000
        databases:
          default:
            host: ${DATABASE_HOST}
            database: ${DATABASE_NAME}
            user: ${DATABASE_NAME_USER}
            password: ${DATABASE_PASSWORD}
            migrations: true

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin:rw
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@mail.com
      - PGADMIN_DEFAULT_PASSWORD=dev123
    ports:
      - 8083:80

volumes:
  pgadmin_data:
  data-prisma:
  data-postgresql:
